<a href="https://colab.research.google.com/github/erickcorrea3092/AZH_ACE_QSARMODEL/blob/main/3_MorDread_descriptors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://www.youtube.com/watch?v=9i9SY6Nd1Zw

In [2]:
! pip install rdkit
! pip install mordredcommunity

Requirement already satisfied: rdkit in /usr/local/lib/python3.13/dist-packages (2026.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from rdkit) (2.1.3)
Requirement already satisfied: Pillow in /usr/local/lib/python3.13/dist-packages (from rdkit) (11.3.0)
Requirement already satisfied: mordredcommunity in /usr/local/lib/python3.13/dist-packages (2.0.7)
Requirement already satisfied: rdkit in /usr/local/lib/python3.13/dist-packages (from mordredcommunity) (2026.9.1)
Requirement already satisfied: six in /usr/local/lib/python3.13/dist-packages (from mordredcommunity) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from mordredcommunity) (2.1.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.13/dist-packages (from mordredcommunity) (3.7)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from mordredcommunity) (26.3)
Requirement already satisfied: Pillow in /usr/local/lib/python3.13/dist-packages (from rdkit->mordredcommunity) (11.3.0)

In [3]:
from rdkit.Chem import AllChem
from rdkit import Chem
from rdkit.Chem import Descriptors
from rdkit.ML.Descriptors import MoleculeDescriptors
import pandas as pd
import numpy as np
from mordred import Calculator, descriptors

In [4]:
!gdown --id 1aN5NvFWxs1zkkJW6lH0CbU9QikGm7pBR

/usr/local/lib/python3.13/dist-packages/gdown/__main__.py:139: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1aN5NvFWxs1zkkJW6lH0CbU9QikGm7pBR
To: /content/AZH_QSAR.xlsx
100% 634k/634k [00:00<00:00, 46.1MB/s]

In [5]:
dataset = pd.read_excel('AZH_QSAR.xlsx')
dataset.shape

(5829, 16)

In [6]:
dataset.tail()

,Unnamed: 0,QED,MolWt,LogP,HAC,RB,TPSA,HBA,HDB,Activity,SMILES,Structure,Molecule ChEMBL ID,pChEMBL Value,Molecule Name,Cluster_number
5824,5824,0.652274,150.221,2.82402,11,1,20.23,1,1,0,Cc1ccc(C(C)C)cc1O,<rdkit.Chem.rdchem.Mol object at 0x7a28d1c51b60>,CHEMBL281202,NaN,CARVACROL,972
5825,5825,0.497332,124.163,0.51970,9,1,13.11,1,0,0,COc1cccc[n+]1C,<rdkit.Chem.rdchem.Mol object at 0x7a28d1c50a50>,CHEMBL2441685,4.34,NaN,973
5826,5826,0.131806,686.982,7.59140,50,21,83.14,6,2,0,O=C(CCCCCCC(=O)NCCCCCCN1CC[C@H]2COc3ccccc3[C@H...,<rdkit.Chem.rdchem.Mol object at 0x7a28d1c50510>,CHEMBL2113719,5.01,NaN,974
5827,5827,0.519763,357.461,4.24990,27,7,58.53,4,2,1,CCn1cc(CNCc2c[nH]nc2-c2ccc(-c3ccccc3)cc2)cn1,<rdkit.Chem.rdchem.Mol object at 0x7a28d1c02f80>,CHEMBL4765163,6.46,NaN,975
5828,5828,0.446412,132.183,-0.58860,9,0,29.46,2,1,0,C[N+]1(C)CCO[C@H](O)C1,<rdkit.Chem.rdchem.Mol object at 0x7a28d1c02960>,CHEMBL345031,NaN,NaN,976

In [7]:
def canonical_smiles (smiles):
  mols = [Chem.MolFromSmiles(smi) for smi in smiles]
  smiles = [Chem.MolToSmiles(mol) for mol in mols]
  return smiles

In [8]:
Canon_SMILES = canonical_smiles(dataset.SMILES)
len(Canon_SMILES)

5829

In [9]:
#put the smiles in dataframe
dataset['SMILES'] = Canon_SMILES
dataset

,Unnamed: 0,QED,MolWt,LogP,HAC,RB,TPSA,HBA,HDB,Activity,SMILES,Structure,Molecule ChEMBL ID,pChEMBL Value,Molecule Name,Cluster_number
0,0,0.197668,578.805,6.51442,43,11,73.39,6,2,1,Cc1c(N2CCN(C)CC2)nc2ccccc2c1C(=O)NCCCCCCCNc1c2...,<rdkit.Chem.rdchem.Mol object at 0x7a28d1c50970>,CHEMBL195241,8.39,NaN,1
1,1,0.385319,358.442,3.10360,26,10,89.32,6,2,1,O=[N+]([O-])OCCCNCCCNc1c2c(nc3ccccc13)CCCC2,<rdkit.Chem.rdchem.Mol object at 0x7a28d16df760>,CHEMBL270491,8.19,NaN,1
2,2,0.653235,310.485,5.80432,23,7,24.92,2,1,1,CCCCCCCNc1c2c(nc3cc(C)ccc13)CCCC2,<rdkit.Chem.rdchem.Mol object at 0x7a28d1c505f0>,CHEMBL61221,6.89,NaN,1
3,3,0.038102,638.884,7.00050,48,14,104.90,6,5,1,Nc1ccc2c(c1)c(-c1ccccc1)[n+](CCCNCCCNCCCNc1c3c...,<rdkit.Chem.rdchem.Mol object at 0x7a28d1c03290>,CHEMBL179455,8.81,NaN,1
4,4,0.154825,595.618,10.01430,42,10,49.84,4,2,1,Clc1ccc2c(NCCCCCCCNc3c4c(nc5cc(Cl)ccc35)-c3ccc...,<rdkit.Chem.rdchem.Mol object at 0x7a28d171e340>,CHEMBL1819177,7.92,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5824,5824,0.652274,150.221,2.82402,11,1,20.23,1,1,0,Cc1ccc(C(C)C)cc1O,<rdkit.Chem.rdchem.Mol object at 0x7a28d1c51b60>,CHEMBL281202,NaN,CARVACROL,972
5825,5825,0.497332,124.163,0.51970,9,1,13.11,1,0,0,COc1cccc[n+]1C,<rdkit.Chem.rdchem.Mol object at 0x7a28d1c50a50>,CHEMBL2441685,4.34,NaN,973
5826,5826,0.131806,686.982,7.59140,50,21,83.14,6,2,0,O=C(CCCCCCC(=O)NCCCCCCN1CC[C@H]2COc3ccccc3[C@H...,<rdkit.Chem.rdchem.Mol object at 0x7a28d1c50510>,CHEMBL2113719,5.01,NaN,974
5827,5827,0.519763,357.461,4.24990,27,7,58.53,4,2,1,CCn1cc(CNCc2c[nH]nc2-c2ccc(-c3ccccc3)cc2)cn1,<rdkit.Chem.rdchem.Mol object at 0x7a28d1c02f80>,CHEMBL4765163,6.46,NaN,975
5828,5828,0.446412,132.183,-0.58860,9,0,29.46,2,1,0,C[N+]1(C)CCO[C@H](O)C1,<rdkit.Chem.rdchem.Mol object at 0x7a28d1c02960>,CHEMBL345031,NaN,NaN,976

In [10]:
#create a list for duplicate SMILES

duplicates_smiles = dataset[dataset['SMILES'].duplicated()]['SMILES'].values
len(duplicates_smiles)

116

In [11]:
#Create a list for duplicate smiles
dataset[dataset['SMILES'].isin(duplicates_smiles)].sort_values(by=['SMILES'])

,Unnamed: 0,QED,MolWt,LogP,HAC,RB,TPSA,HBA,HDB,Activity,SMILES,Structure,Molecule ChEMBL ID,pChEMBL Value,Molecule Name,Cluster_number
3775,3775,0.797841,286.375,2.6894,21,4,32.78,3,0,0,C#CCN(C)C1CCc2c(OC(=O)N(C)CC)cccc21,<rdkit.Chem.rdchem.Mol object at 0x7a28d172b7d0>,CHEMBL1190983,5.40,NaN,199
3777,3777,0.797841,286.375,2.6894,21,4,32.78,3,0,0,C#CCN(C)C1CCc2c(OC(=O)N(C)CC)cccc21,<rdkit.Chem.rdchem.Mol object at 0x7a28d1c40350>,CHEMBL542016,4.83,NaN,199
3392,3392,0.791541,272.348,2.2993,20,3,32.78,3,0,0,C#CCN(C)C1CCc2cccc(OC(=O)N(C)C)c21,<rdkit.Chem.rdchem.Mol object at 0x7a28d17263b0>,CHEMBL1193856,NaN,NaN,156
3391,3391,0.791541,272.348,2.2993,20,3,32.78,3,0,0,C#CCN(C)C1CCc2cccc(OC(=O)N(C)C)c21,<rdkit.Chem.rdchem.Mol object at 0x7a28d168a570>,CHEMBL545331,5.16,NaN,156
3394,3394,0.842631,258.321,1.9571,19,3,41.57,3,1,0,C#CCNC1CCc2c(OC(=O)N(C)C)cccc21,<rdkit.Chem.rdchem.Mol object at 0x7a28d16b0900>,CHEMBL1195259,4.07,NaN,156
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4763,4763,0.522778,375.472,4.8595,28,5,65.29,4,2,1,Oc1cc2cc3c(CCC4CCN(Cc5ccccc5)CC4)[nH]oc3cc2n1,<rdkit.Chem.rdchem.Mol object at 0x7a28d1707450>,CHEMBL329012,9.48,ICOPEZIL MALEATE,363
2333,2333,0.643096,372.516,4.8578,28,7,41.05,4,1,1,c1ccc(CN2CCC(CCNc3ccc(-c4ccccc4)nn3)CC2)cc1,<rdkit.Chem.rdchem.Mol object at 0x7a28d1679e00>,CHEMBL25412,6.92,NaN,74
2327,2327,0.643096,372.516,4.8578,28,7,41.05,4,1,1,c1ccc(CN2CCC(CCNc3ccc(-c4ccccc4)nn3)CC2)cc1,<rdkit.Chem.rdchem.Mol object at 0x7a28d1c56880>,CHEMBL3215535,6.85,NaN,74
262,262,0.220114,492.711,8.0151,37,10,49.84,4,2,1,c1ccc2c(NCCCCCCCNc3c4c(nc5ccccc35)CCCC4)c3c(nc...,<rdkit.Chem.rdchem.Mol object at 0x7a28d16bb6f0>,CHEMBL3752685,9.09,NaN,1
146,146,0.220114,492.711,8.0151,37,10,49.84,4,2,1,c1ccc2c(NCCCCCCCNc3c4c(nc5ccccc35)CCCC4)c3c(nc...,<rdkit.Chem.rdchem.Mol object at 0x7a28d1c41d90>,CHEMBL32823,9.09,NaN,1

###2.Drop duplicates value

In [12]:
dataset_new = dataset.drop_duplicates(subset=['SMILES'])
len(dataset_new)

5713

In [13]:
dataset_new

,Unnamed: 0,QED,MolWt,LogP,HAC,RB,TPSA,HBA,HDB,Activity,SMILES,Structure,Molecule ChEMBL ID,pChEMBL Value,Molecule Name,Cluster_number
0,0,0.197668,578.805,6.51442,43,11,73.39,6,2,1,Cc1c(N2CCN(C)CC2)nc2ccccc2c1C(=O)NCCCCCCCNc1c2...,<rdkit.Chem.rdchem.Mol object at 0x7a28d1c50970>,CHEMBL195241,8.39,NaN,1
1,1,0.385319,358.442,3.10360,26,10,89.32,6,2,1,O=[N+]([O-])OCCCNCCCNc1c2c(nc3ccccc13)CCCC2,<rdkit.Chem.rdchem.Mol object at 0x7a28d16df760>,CHEMBL270491,8.19,NaN,1
2,2,0.653235,310.485,5.80432,23,7,24.92,2,1,1,CCCCCCCNc1c2c(nc3cc(C)ccc13)CCCC2,<rdkit.Chem.rdchem.Mol object at 0x7a28d1c505f0>,CHEMBL61221,6.89,NaN,1
3,3,0.038102,638.884,7.00050,48,14,104.90,6,5,1,Nc1ccc2c(c1)c(-c1ccccc1)[n+](CCCNCCCNCCCNc1c3c...,<rdkit.Chem.rdchem.Mol object at 0x7a28d1c03290>,CHEMBL179455,8.81,NaN,1
4,4,0.154825,595.618,10.01430,42,10,49.84,4,2,1,Clc1ccc2c(NCCCCCCCNc3c4c(nc5cc(Cl)ccc35)-c3ccc...,<rdkit.Chem.rdchem.Mol object at 0x7a28d171e340>,CHEMBL1819177,7.92,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5824,5824,0.652274,150.221,2.82402,11,1,20.23,1,1,0,Cc1ccc(C(C)C)cc1O,<rdkit.Chem.rdchem.Mol object at 0x7a28d1c51b60>,CHEMBL281202,NaN,CARVACROL,972
5825,5825,0.497332,124.163,0.51970,9,1,13.11,1,0,0,COc1cccc[n+]1C,<rdkit.Chem.rdchem.Mol object at 0x7a28d1c50a50>,CHEMBL2441685,4.34,NaN,973
5826,5826,0.131806,686.982,7.59140,50,21,83.14,6,2,0,O=C(CCCCCCC(=O)NCCCCCCN1CC[C@H]2COc3ccccc3[C@H...,<rdkit.Chem.rdchem.Mol object at 0x7a28d1c50510>,CHEMBL2113719,5.01,NaN,974
5827,5827,0.519763,357.461,4.24990,27,7,58.53,4,2,1,CCn1cc(CNCc2c[nH]nc2-c2ccc(-c3ccccc3)cc2)cn1,<rdkit.Chem.rdchem.Mol object at 0x7a28d1c02f80>,CHEMBL4765163,6.46,NaN,975
5828,5828,0.446412,132.183,-0.58860,9,0,29.46,2,1,0,C[N+]1(C)CCO[C@H](O)C1,<rdkit.Chem.rdchem.Mol object at 0x7a28d1c02960>,CHEMBL345031,NaN,NaN,976

In [14]:
# prompt: en dataset_new en la columna pChEMBL Value hay elementos vacios y cuantos?

print(f"Number of empty values in 'pChEMBL Value': {dataset_new['pChEMBL Value'].isnull().sum()}")

Number of empty values in 'pChEMBL Value': 459

In [15]:
# prompt: elemina de dataset_new todos los elementos con elementos vacios en la columna pChEMBL Value

dataset_new.dropna(subset=['pChEMBL Value'], inplace=True)

#print(f"Number of empty values in 'pChEMBL Value' after dropping: {dataset_new['pChEMBL Value'].isnull().sum()}")
#print(f"Shape of dataset_new after dropping empty values: {dataset_new.shape}")

/tmp/ipykernel_2334/4174445245.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset_new.dropna(subset=['pChEMBL Value'], inplace=True)

Calculate descriptors using Mordred 1826 molecular descriptors

In [16]:
dataset_new.shape

(5254, 16)

In [17]:
dataset_new.reset_index(drop=True, inplace=True)

In [18]:
def All_Mordred_descriptors(data):
  calc = Calculator(descriptors, ignore_3D=True)
  mols = [Chem.MolFromSmiles(smi) for smi in data]

  #pandas df
  df = calc.pandas(mols)
  return df

In [19]:
mordred_descriptors = All_Mordred_descriptors(dataset_new['SMILES'])

100%|██████████| 5254/5254 [20:24<00:00,  4.29it/s]

In [20]:
mordred_descriptors.shape

(5254, 1613)

In [21]:
#mordred_descriptors

In [22]:
# prompt: list of a dataframe columns

#list(mordred_descriptors.columns)

In [23]:
mordred_descriptors.tail(25)

,ABC,ABCGG,nAcid,nBase,SpAbs_A,SpMax_A,SpDiam_A,SpAD_A,SpMAD_A,LogEE_A,...,SRW10,TSRW10,MW,AMW,WPath,WPol,Zagreb1,Zagreb2,mZagreb1,mZagreb2
5229,13.102778,11.473917,0,0,19.938037,2.536708,4.902266,19.938037,1.246127,3.753977,...,9.991819,65.672777,229.095023,7.390162,389,25,94.0,114.0,5.979167,3.194444
5230,23.391543,17.021601,0,1,38.751077,2.433805,4.813653,38.751077,1.336244,4.324991,...,10.304844,80.548583,385.190260,7.407505,2559,44,160.0,190.0,7.361111,6.194444
5231,19.913028,15.815371,0,0,32.261886,2.563127,5.024081,32.261886,1.290475,4.176070,...,10.390440,74.816089,338.079038,8.668693,1398,46,140.0,172.0,8.472222,5.388889
5232,23.598392,18.619599,0,0,38.672970,2.521365,4.912607,38.672970,1.289099,4.337087,...,10.350638,80.146797,462.078094,9.060355,2387,49,160.0,190.0,9.722222,6.527778
5233,16.429865,12.869349,0,1,27.316681,2.438062,4.876124,27.316681,1.300794,3.979137,...,9.982160,54.995125,286.168128,6.655073,974,33,110.0,129.0,6.527778,4.611111
5234,28.300850,19.380229,0,2,47.965063,2.421112,4.842224,47.965063,1.332363,4.517231,...,10.469965,72.620233,479.217304,7.606624,4659,58,190.0,223.0,9.722222,7.972222
5235,25.270223,17.518147,0,0,42.504917,2.592708,5.136069,42.504917,1.371126,4.407424,...,10.649061,82.041259,409.179027,7.577389,2739,58,178.0,220.0,7.583333,6.611111
5236,21.177412,17.165333,1,1,35.680922,2.575547,5.026700,35.680922,1.321516,4.244082,...,10.430019,77.338476,366.157957,7.472611,1673,50,148.0,182.0,8.972222,6.000000
5237,47.220645,29.589659,0,2,78.944538,2.366006,4.732012,78.944538,1.273299,5.023472,...,10.786697,100.652429,920.286563,8.072689,28871,91,304.0,344.0,19.277778,14.055556
5238,8.803119,8.280547,0,0,14.429375,2.259889,4.519777,14.429375,1.202448,3.375766,...,9.050758,42.198688,208.068687,7.174782,205,13,56.0,60.0,4.923611,2.750000
5239,22.971131,17.367102,0,1,35.642083,2.383446,4.766892,35.642083,1.188069,4.297670,...,10.144589,65.272501,412.321006,5.726681,3302,39,150.0,164.0,11.770833,6.416667
5240,24.457778,19.125119,0,1,38.929548,2.629264,5.221860,38.929548,1.255792,4.381397,...,10.762763,82.173663,426.324629,5.840063,2666,62,174.0,216.0,11.986111,6.638889
5241,25.300335,19.578989,0,0,40.556451,2.482784,4.965568,40.556451,1.267389,4.401873,...,10.529453,68.448741,442.089997,8.841800,2839,57,174.0,208.0,12.055556,6.805556
5242,23.099582,18.345312,0,2,37.838273,2.395491,4.774946,37.838273,1.261276,4.316823,...,10.236919,78.660198,418.161661,8.199248,2834,45,154.0,178.0,10.701389,6.611111
5243,26.777606,18.760460,0,0,43.078646,2.378929,4.697231,43.078646,1.267019,4.451544,...,10.290958,83.994994,491.149047,8.468087,4415,47,178.0,202.0,10.812500,7.263889
5244,27.923478,22.366757,0,0,43.010382,2.519172,4.995548,43.010382,1.228868,4.494202,...,10.627576,87.788908,533.041486,11.105031,3910,57,194.0,229.0,13.687500,7.138889
5245,23.829102,18.681381,0,0,39.137807,2.374954,4.749909,39.137807,1.262510,4.342559,...,10.171490,66.446138,434.166414,7.616955,2842,46,156.0,178.0,10.861111,6.861111
5246,21.270223,16.705912,0,1,35.966462,2.499819,4.999638,35.966462,1.284516,4.246859,...,10.226694,63.227986,399.207740,6.882892,2125,45,142.0,166.0,9.500000,6.444444
5247,25.472423,18.391538,0,0,43.368123,2.490251,4.980502,43.368123,1.314186,4.419071,...,10.386932,69.095407,454.232853,7.210045,3336,53,170.0,199.0,9.861111,7.472222
5248,30.843584,22.643373,0,0,49.056964,2.704089,5.408179,49.056964,1.290973,4.607661,...,11.183824,76.472234,519.225702,7.313038,4128,87,226.0,288.0,13.361111,7.854167
5249,17.177412,14.617126,0,0,28.941652,2.418546,4.742562,28.941652,1.258333,4.036078,...,9.808572,70.652630,318.110338,7.758789,1354,32,112.0,128.0,8.527778,5.333333
5250,20.143738,15.416034,0,0,32.883393,2.489213,4.978426,32.883393,1.264746,4.179094,...,10.177970,60.954139,348.183778,6.963676,1810,41,134.0,156.0,9.000000,5.722222
5251,6.432911,6.255590,0,1,11.203558,2.221583,4.443167,11.203558,1.244840,3.090233,...,8.689296,37.472182,124.075690,6.530299,86,10,40.0,44.0,3.472222,2.194444
5252,38.786132,24.300793,0,2,66.451866,2.490385,4.901642,66.451866,1.329037,4.831766,...,10.685126,103.877223,686.477106,6.129260,16155,73,254.0,294.0,12.333333,11.305556
5253,21.091883,16.190112,0,1,36.392514,2.395310,4.741394,36.392514,1.347871,4.231761,...,10.031925,77.434826,357.195346,7.143907,2202,37,140.0,163.0,6.527778,6.083333

In [24]:
dataset_new.tail()

,Unnamed: 0,QED,MolWt,LogP,HAC,RB,TPSA,HBA,HDB,Activity,SMILES,Structure,Molecule ChEMBL ID,pChEMBL Value,Molecule Name,Cluster_number
5249,5822,0.346302,318.325,2.1740,23,7,93.06,6,2,0,COC/C(C=O)=C\CCC1=CC(c2cc(O)ccc2O)OC1=O,<rdkit.Chem.rdchem.Mol object at 0x7a28d1c52420>,CHEMBL5197965,5.07,NaN,970
5250,5823,0.564648,348.446,3.7085,26,5,62.82,3,1,0,CC(C)=CCCC(C)CC=c1ccc(=O)c2[nH]c3cccc(=O)c3nc12,<rdkit.Chem.rdchem.Mol object at 0x7a28d1c51cb0>,CHEMBL2071424,5.58,GERANYLPHENAZINEDIOL,971
5251,5825,0.497332,124.163,0.5197,9,1,13.11,1,0,0,COc1cccc[n+]1C,<rdkit.Chem.rdchem.Mol object at 0x7a28d1c50a50>,CHEMBL2441685,4.34,NaN,973
5252,5826,0.131806,686.982,7.5914,50,21,83.14,6,2,0,O=C(CCCCCCC(=O)NCCCCCCN1CC[C@H]2COc3ccccc3[C@H...,<rdkit.Chem.rdchem.Mol object at 0x7a28d1c50510>,CHEMBL2113719,5.01,NaN,974
5253,5827,0.519763,357.461,4.2499,27,7,58.53,4,2,1,CCn1cc(CNCc2c[nH]nc2-c2ccc(-c3ccccc3)cc2)cn1,<rdkit.Chem.rdchem.Mol object at 0x7a28d1c02f80>,CHEMBL4765163,6.46,NaN,975

In [25]:
# prompt: combina dataset_new y mordred_descriptors y elimna la primera columna

# Combinar los dos DataFrames
combined_df = pd.concat([dataset_new, mordred_descriptors], axis=1)

# Eliminar la primera columna (asumiendo que es la primera columna de `dataset_new`)
# Si la primera columna de `mordred_descriptors` también necesita ser eliminada,
# se puede usar `combined_df = combined_df.iloc[:, 1:]`
combined_df = combined_df.iloc[:, 1:]

combined_df.tail()

,QED,MolWt,LogP,HAC,RB,TPSA,HBA,HDB,Activity,SMILES,...,SRW10,TSRW10,MW,AMW,WPath,WPol,Zagreb1,Zagreb2,mZagreb1,mZagreb2
5249,0.346302,318.325,2.1740,23,7,93.06,6,2,0,COC/C(C=O)=C\CCC1=CC(c2cc(O)ccc2O)OC1=O,...,9.808572,70.652630,318.110338,7.758789,1354,32,112.0,128.0,8.527778,5.333333
5250,0.564648,348.446,3.7085,26,5,62.82,3,1,0,CC(C)=CCCC(C)CC=c1ccc(=O)c2[nH]c3cccc(=O)c3nc12,...,10.177970,60.954139,348.183778,6.963676,1810,41,134.0,156.0,9.000000,5.722222
5251,0.497332,124.163,0.5197,9,1,13.11,1,0,0,COc1cccc[n+]1C,...,8.689296,37.472182,124.075690,6.530299,86,10,40.0,44.0,3.472222,2.194444
5252,0.131806,686.982,7.5914,50,21,83.14,6,2,0,O=C(CCCCCCC(=O)NCCCCCCN1CC[C@H]2COc3ccccc3[C@H...,...,10.685126,103.877223,686.477106,6.129260,16155,73,254.0,294.0,12.333333,11.305556
5253,0.519763,357.461,4.2499,27,7,58.53,4,2,1,CCn1cc(CNCc2c[nH]nc2-c2ccc(-c3ccccc3)cc2)cn1,...,10.031925,77.434826,357.195346,7.143907,2202,37,140.0,163.0,6.527778,6.083333

In [26]:
# prompt: descarga mordred_descriptors como un excel

# Assuming mordred_descriptors DataFrame is already created as in your provided code

# Save the Mordred descriptors to an Excel file
combined_df.to_csv('AZH_descriptors_1.csv', index=False)